config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/projects')

  resources :messages
  resources :projects
  resources :companies

  devise_for :admins
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users

  resources :projects do
    resources :input_files
    resources :quotations
    resources :invoices
    resources :output_files
  end
  
  get 'pages/info'
  get 'companies/:id/invitations/new' => 'invitations#new'
  post 'companies/:id/invitations' => 'invitations#create', :as => :invitations
  post 'projects/:id/accept' => 'projects#accept'
  post 'projects/:id/reject' => 'projects#reject'
  post 'companies/:id/leave' => 'companies#leave'
  get 'projects/:id/manage', to: 'projects#manage', :as => :manage_project
  post 'users/:id/grantManager' => 'users#grantManager'
  post 'users/:id/removeManagerPriv' => 'users#removeManagerPriv'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/storage/inputFiles/:id/:basename.:extension' => 'input_files#download'
  get '/storage/quotations/:id/:basename.:extension' => 'quotations#download'
  get '/storage/invoices/:id/:basename.:extension' => 'invoices#download'
  get '/storage/outputFiles/:id/:basename.:extension' => 'output_files#download'

  match 'projects/:project_id/input_files/:id' => 'input_files#destroy', :via => :delete, :as => :destroy_input_file
  match 'projects/:project_id/quotations/:id' => 'quotations#destroy', :via => :delete, :as => :destroy_quotation
  match 'projects/:project_id/invoices/:id' => 'invoices#destroy', :via => :delete, :as => :destroy_invoice
  match 'projects/:project_id/output_files/:id' => 'output_files#destroy', :via => :delete, :as => :destroy_output_file

end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
	mount_uploader :file_path, FileUploader
	belongs_to :project
	belongs_to :currency
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:destroy, :update, :download]
  before_action :set_project, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :set_project_download, only: [:download]
  before_action :check_company
  before_action :check_auth

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = @project.quotations
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)
    respond_to do |format|
      if @quotation.save
        @quotation.update_attribute(:project_id, params[:project_id])
        # Change the project's status if Pending
        if @project.status == 'Pending'
          @project.update_attribute(:status, 'Quote')
          # Send email notification about the modification of the status
          ExampleMailer.status(@project).deliver
        end
        # Send email notification to the owner of the project
        ExampleMailer.new_quotation(@project).deliver
        format.html { redirect_to @project, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    # Change the status to Pending if there is no quotation anymore
    if @project.quotations.first == @quotation && @project.quotations.size == 1 && (@project.status == 'Quote' || @project.status == 'Ongoing')
      @project.update_attribute(:status, 'Pending')
      # Send email notification about the modification of the status
      ExampleMailer.status(@project).deliver
    end
    # Set project attributes relative to the quotation with the default values
    @project.update_attribute(:confirmation, false)
    @project.update_attribute(:deadline, nil)
    @project.update_attribute(:cost, nil)
    @project.update_attribute(:currency_id, nil)
    # Destroy the quotation
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Download the file
  def download
    path = "#{@quotation.file_path}"
    send_file path, :x_sendfile=>true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Set the project of the file
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Set the project of the file to download
    def set_project_download
      @project = Project.find(@quotation.project_id)
    end

    # Check if the current user belongs to a company or if they are an administrator or a project manager.
    def check_company
      if current_user.company == nil && !current_user.manager? && !current_user.admin?
        redirect_to new_company_path, :alert => "You have to create or be invited by a company before access to the website." and return
      end
    end

    # Check if the current user has the right to manage the client files of the current project.
    def check_auth
      if @project.project_owner_id != current_user.id && !current_user.admin? && current_user.id != @project.project_manager_id && !(current_user.company == @project.project_owner.company && current_user.company_admin?)
        redirect_to projects_path, :alert => "Access denied." and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:file_path, :project_id, :name, :cost, :deadline, :currency_id)
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.erb
<%= form_for [@project, @quotation] do |f| %>
  <% if @quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>
      <ul>
      <% @quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file_path %><br>
    <%= f.file_field :file_path %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
    <%= f.collection_select(:currency_id, Currency.all, :id, :title, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline, {:include_blank => true, :default => nil} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotations/_index.html.erb
<h3>Quotations</h3>
<% if @project.quotations.size != 0 %>
  <table>
    <thead>
      <tr>
        <th><center>Name</center></th>
        <th><center>File</center></th>
        <th><center>Cost</center></th>
        <th><center>Deadline</center></th>
        <th><center>Actions</center></th>
        <th colspan="2"></th>
      </tr>
    <thead>
    <tbody>
      <% @project.quotations.each do |quotation| %>
        <tr>
          <% if quotation.name != nil && quotation.name != "" %>
            <td><center><%= quotation.name %></center></td>
          <% else %>
            <td><center>N/A</center></td>
          <% end %>
          <td><center><%= link_to File.basename(quotation.file_path.url.to_s), "/storage/quotations/#{quotation.id}/#{File.basename(quotation.file_path.url.to_s)}" %></center></td>
          <% if quotation.cost != nil %>
            <td><center><%= quotation.cost %>
              <% if quotation.currency != nil %>
                <%= quotation.currency.title %>
                <% end %>
            </center></td>
          <% else %>
            <td><center>N/A</center></td>
          <% end %>
          <% if quotation.deadline != nil && quotation.deadline != "" %>
            <td><center><%= quotation.deadline %></center></td>
          <% else %>
            <td><center>N/A</center></td>
          <% end %>
          <% if quotation.file_path.url != nil %>
            <td><center><%= link_to "Download", "/storage/quotations/#{quotation.id}/#{File.basename(quotation.file_path.url.to_s)}" %></center></td>
          <% end %>
          <% if current_user.admin? || (current_user.manager? && current_user.id == @project.project_manager_id) %>
            <td><center><%= link_to "Destroy", destroy_quotation_path(@project.id, quotation.id), method: :delete, data: { confirm: "Are you sure ?" } %></center></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<p>No quotation submitted.</p>
<% end %>

<% if current_user.admin? || (current_user.manager? && current_user.id == @project.project_manager_id) %>
  <%= link_to "Add Quotation", new_project_quotation_path(@project) %>
<% end %>

app/views/quotations/new.html.erb
<h1>New Quotation</h1>

<%= render 'form' %>

<%= link_to 'Back', @project %>