config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/projects')

  resources :messages
  resources :projects
  resources :companies

  devise_for :admins
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users

  resources :projects do
    resources :input_files
    resources :quotations
    resources :invoices
    resources :output_files
  end
  
  get 'pages/info'
  get 'companies/:id/invitations/new' => 'invitations#new'
  post 'companies/:id/invitations' => 'invitations#create', :as => :invitations
  post 'projects/:id/accept' => 'projects#accept'
  post 'projects/:id/reject' => 'projects#reject'
  post 'companies/:id/leave' => 'companies#leave'
  get 'projects/:id/manage', to: 'projects#manage', :as => :manage_project
  post 'users/:id/grantManager' => 'users#grantManager'
  post 'users/:id/removeManagerPriv' => 'users#removeManagerPriv'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/storage/inputFiles/:id/:basename.:extension' => 'input_files#download'
  get '/storage/quotations/:id/:basename.:extension' => 'quotations#download'
  get '/storage/invoices/:id/:basename.:extension' => 'invoices#download'
  get '/storage/outputFiles/:id/:basename.:extension' => 'output_files#download'

  match 'projects/:project_id/input_files/:id' => 'input_files#destroy', :via => :delete, :as => :destroy_input_file
  match 'projects/:project_id/quotations/:id' => 'quotations#destroy', :via => :delete, :as => :destroy_quotation
  match 'projects/:project_id/invoices/:id' => 'invoices#destroy', :via => :delete, :as => :destroy_invoice
  match 'projects/:project_id/output_files/:id' => 'output_files#destroy', :via => :delete, :as => :destroy_output_file

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :project_manager, :class_name => 'User'
	belongs_to :project_owner, :class_name => 'User'
	belongs_to :category
	belongs_to :currency
	belongs_to :company
	has_many :input_files, :dependent => :destroy
	has_many :quotations, :dependent => :destroy
	has_many :invoices, :dependent => :destroy
	has_many :output_files, :dependent => :destroy
	has_many :messages, :dependent => :destroy

	validates :title, :description, :category_id, presence: true
	validates :cost, numericality: { only_integer: true }, :allow_blank => true
	validates :urgency, presence: true, inclusion: { in: ["Low", "Middle", "High"]}
	def self.search(query)
		where("title like ?", "%#{query}%")
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_project, only: [:show, :edit, :update, :destroy, :accept, :reject, :manage, :download]
  before_action :check_company
  before_action :check_auth, only: [:show, :update, :destroy, :accept, :reject]
  

  # GET /projects
  # GET /projects.json
  def index
    # Get the projects to display according to the role of the user
    if current_user.admin?
      @projects = Project.all
      print 'ADMIn PROJECT '+@projects.to_s
    elsif current_user.manager?
      @projects = Project.where('project_manager_id=? OR project_owner_id=?', current_user.id, current_user.id)
    elsif current_user.company_admin?
      @projects = current_user.company.project_owned
    else
      @projects = current_user.project_owned
    end
    # Search and then sort
    if params[:search]
      @projects = @projects.search(params[:search]).order(sort_column + ' ' + sort_direction)
    end
    # Sort the projects
    @projects = @projects.order(sort_column + ' ' + sort_direction)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    # Can not edit the project when the status is Delivered or Closed if the user is not admin or PM of the project
    if (@project.status == "Delivered" || @project.status == "Closed") && !current_user.admin? && !(current_user.manager? && current_user.id == @project.project_manager_id)
      redirect_to projects_path, :alert => "The project is closed, you can't edit it." and return
    end
  end

  # Set advanced attributes for the project
  def manage
    # Can not manage the project if the user is not admin or PM of the project
    if !current_user.admin? && !(current_user.manager? && current_user.id == @project.project_manager_id)
      redirect_to projects_path, :alert => "You can not manage this project." and return
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        @project.update_attribute(:status, 'Pending')
        @project.update_attribute(:project_owner_id, current_user.id)
        @project.update_attribute(:company_id, current_user.company_id)
        # Send mail notification to the admins and to the current user about the creation of the project
        ExampleMailer.create_project_admin(@project).deliver
        ExampleMailer.create_project(@project).deliver
        format.html { redirect_to new_project_input_file_path(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    # Update of the management form
    if params[:save]
      respond_to do |format|
        manager = @project.project_manager_id
        if @project.update(project_params)
          if manager != @project.project_manager_id
            # Notify the new manager by email
            ExampleMailer.new_manager(@project).deliver
          end
          # Notify the owner of the project about the management of its project
          ExampleMailer.manage(@project).deliver
          format.html { redirect_to @project, notice: 'Project was successfully managed.' }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :manage }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    # Update of the regular form
    else
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def accept
    # Check if the user is authorized to accept the project
    if @project.status != 'Quote' || (current_user != @project.project_owner && !(current_user.company_admin? && current_user.company_id == @project.company_id))
      redirect_to projects_path, :alert => "Access denied." and return
    end
    # Set the attributes of the project with the values of the last quotation
    @quotation = @project.quotations.last
    @project.update_attribute(:cost, @quotation.cost)
    @project.update_attribute(:currency_id, @quotation.currency_id)
    @project.update_attribute(:deadline, @quotation.deadline)
    @project.update_attribute(:confirmation, true)
    @project.update_attribute(:status, 'Ongoing')
    @project.update_attribute(:starting, Date.today)
    # Notify the admins and the PM that the project is accepted
    ExampleMailer.accept_project_admin(@project).deliver
    redirect_to @project and return
  end

  def reject
    # Check if the user is authorized to reject the project
    if @project.status != 'Ongoing' || (current_user != @project.project_owner && !(current_user.company_admin? && current_user.company_id == @project.company_id))
      redirect_to projects_path, :alert => "Access denied." and return
    end
    # Reset the attributes of the project with default values
    @project.update_attribute(:cost, nil)
    @project.update_attribute(:deadline, nil)
    @project.update_attribute(:confirmation, false)
    @project.update_attribute(:status, 'Quote')
    @project.update_attribute(:starting, Date.today)
    # Notify the admins and the PM that the project is rejected
    ExampleMailer.reject_project_admin(@project).deliver
    redirect_to @project and return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def check_company
      # Check if the user is invited in a new company
      invit = Invitation.all.where(email: current_user.email).where(done: false)
      if invit.size != 0
        current_user.update_attribute(:company_id, invit.first.company_id)
        invit.first.update_attribute(:done, true)
      end
      # Check if the current user belongs to a company or if they are an administrator or a project manager.
      if current_user.company == nil && !current_user.manager? && !current_user.admin?
        redirect_to new_company_path, :alert => "You have to create or be invited by a company before access to the website." and return
      end
    end

    # Check if the current user has the rights to see, edit, update, accept, reject or destroy a project.
    def check_auth
      if @project.project_owner_id != current_user.id && !current_user.admin? && current_user.id != @project.project_manager_id && !(current_user.company == @project.project_owner.company && current_user.company_admin?)
        redirect_to projects_path, :alert => "Access denied." and return
      end
    end

    # Sort column
    def sort_column  
      Project.column_names.include?(params[:sort]) ? params[:sort] : "created_at"  
    end   
    
    # Sort direction
    def sort_direction  
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"  
    end  

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :status, :description, :cost, :instruction, :category_id, :urgency, :deadline, :starting, :project_manager_id, :currency_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <% if @project.status != nil %>
    <div class="field">
      <strong>Status:</strong>
      <%= @project.status %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :instruction %><br>
    <%= f.text_area :instruction %>
  </div>
  <div class="field">
    <%= f.label :urgency %><br>
    <%= f.label :urgency, "Low", :value => "Low"  %>
    <%= f.radio_button :urgency, "Low" %>
    
    <%= f.label :urgency, "Middle", :value => "Middle"  %>
    <%= f.radio_button :urgency, "Middle", :checked => true %>
    
    <%= f.label :urgency, "High", :value => "High"  %>
    <%= f.radio_button :urgency, "High" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<center><h1>DASHBOARD</h1></center>
<center>
<table width=80% class="container">
  <thead>
    <tr>
      <th> Sort by: <%= sortable "category_id", "Category" %>, <%= sortable "title" %>, <%= sortable "status" %>, <%= sortable "deadline" %>, <%= sortable "cost" %>, <%= sortable "created_at", "Creation" %></th>
      <th align=right><%= link_to 'New Project', new_project_path %></th>
    </tr>
  </thead>
</table>
</center>

<h3>PENDING PROJECTS</h3>
<table width=100%>
  <thead>
    <tr>
      <th width="10%"><center>Category</center></th>
      <th width="20%"><center>Title</center></th>
      <th width="10%"><center>Status</center></th>
      <th width="10%"><center>Deadline</center></th>
      <th width="5%"><center>Cost</center></th>
      <th width="15%"><center>Project Manager</center></th>
      <th width="15%"><center>User</center></th>
      <th colspan="15%"><center>ACTIONS</center></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <% if project.status == "Pending" || project.status == "Quote" %>
      <tr>
        <td><center><%= project.category.name %></center></td>
        <td><center><%= project.title %></center></td>
        <td><center><%= project.status %></center></td>
        <% if project.deadline != nil %>
          <td><center><%= project.deadline %></center></td>
        <% else %>
          <td><center>N/A</center></td>
        <% end %>
        <% if project.cost != nil %>
          <td><center><%= project.cost %>
            <% if project.currency != nil %>
              <%= project.currency.title %>
            <% end %>
          </center></td>
        <% else %>
          <td><center>N/A</center></td>
        <% end %>
        <% if project.project_manager != nil %>
        <td><center><%= project.project_manager.firstname %></center></td>
        <% else %>
        <td><center>N/A</center></td>
        <% end %>
        <% if project.project_owner != nil %>
        <td><center><%= project.project_owner.firstname %> <%= project.project_owner.lastname %></center></td>
        <% else %>
        <td><center>N/A</center></td>
        <% end %>
        <td><center><%= link_to 'Show', project %></center></td>
        <% if current_user.admin? || (current_user.manager? && current_user.id == project.project_manager_id) || project.project_owner == current_user %>
        <td><center><%= link_to 'Edit', edit_project_path(project) %></center></td>
        <% end %>
        <td><center><%= link_to 'Destroy', project, method: :delete, data: { confirm: "Are you sure?\nAll the files attached to the project will be deleted." } %></center></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<center>
<% if @projects.where(status: "Pending").size == 0 && @projects.where(status: "Quote").size == 0 %>
  <h4>No pending projects</h4>
<% end %>
</center>

<h3>ONGOING PROJECTS</h3>
<table width=100%>
  <thead>
    <tr>
      <th width="10%"><center>Category</center></th>
      <th width="15%"><center>Title</center></th>
      <th width="10%"><center>Status</center></th>
      <th width="10%"><center>Deadline</center></th>
      <th width="5%"><center>Progress</center></th>
      <th width="5%"><center>Cost</center></th>
      <th width="15%"><center>Project Manager</center></th>
      <th width="15%"><center>User</center></th>
      <th colspan="15%"><center>ACTIONS</center></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <% if project.status == "Ongoing" %>
      <tr>
        <td><center><%= project.category.name %></center></td>
        <td><center><%= project.title %></center></td>
        <td><center><%= project.status %></center></td>

        <% if project.deadline != nil %>
          <td><center><%= project.deadline %></center></td>
        <% else %>
          <td><center>N/A</center></td>
        <% end %>

        <% if project.deadline != nil && project.starting != nil %>
          <% if (project.deadline - project.starting).to_i == 0 %>
            <td><center>100%</center></td>
          <% else %>
            <td><center><%= ((100/(project.deadline - project.starting).to_i * (Date.today - project.starting)).to_i).to_s+'%'%></center></td>
          <% end %>
        <% else %>
          <td><center>N/A</center></td>
        <% end %>

        <% if project.cost != nil %>
          <td><center><%= project.cost %>
            <% if project.currency != nil %>
              <%= project.currency.title %>
            <% end %>
          </center></td>
        <% else %>
          <td><center>N/A</center></td>
        <% end %>

        <% if project.project_manager != nil %>
          <td><center><%= project.project_manager.firstname %></center></td>
        <% else %>
          <td><center>N/A</center></td>
        <% end %>

        <% if project.project_owner != nil %>
        <td><center><%= project.project_owner.firstname %> <%= project.project_owner.lastname %></center></td>
        <% else %>
        <td><center>N/A</center></td>
        <% end %>
        <td><center><%= link_to 'Show', project %></center></td>
        <% if current_user.admin? || (current_user.manager? && current_user.id == project.project_manager_id) || project.project_owner == current_user %>
        <td><center><%= link_to 'Edit', edit_project_path(project) %></center></td>
        <% end %>
        <td><center><%= link_to 'Destroy', project, method: :delete, data: { confirm: "Are you sure?\nAll the files attached to the project will be deleted." } %></center></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<center>
<% if @projects.where(status: "Ongoing").size == 0 %>
  <h4>No on going projects</h4>
<% end %>
</center>

<h3>COMPLETED PROJECTS</h3>
<table width=100%>
  <thead>
    <tr>
      <th width="10%"><center>Category</center></th>
      <th width="20%"><center>Title</center></th>
      <th width="10%"><center>Status</center></th>
      <th width="10%"><center>Deadline</center></th>
      <th width="5%"><center>Cost</center></th>
      <th width="15%"><center>Project Manager</center></th>
      <th width="15%"><center>User</center></th>
      <th colspan="15%"><center>ACTIONS</center></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <% if project.status == "Closed" || project.status == "Delivered" %>
      <tr>
        <td><center><%= project.category.name %></center></td>
        <td><center><%= project.title %></center></td>
        <td><center><%= project.status %></center></td>
        <% if project.deadline != nil %>
          <td><center><%= project.deadline %></center></td>
        <% else %>
          <td><center>N/A</center></td>
        <% end %>
        <% if project.cost != nil %>
          <td><center><%= project.cost %>
            <% if project.currency != nil %>
              <%= project.currency.title %>
            <% end %>
          </center></td>
        <% else %>
          <td><center>N/A</center></td>
        <% end %>
        <% if project.project_manager != nil %>
        <td><center><%= project.project_manager.firstname %></center></td>
        <% else %>
        <td><center>N/A</center></td>
        <% end %>
        <% if project.project_owner != nil %>
        <td><center><%= project.project_owner.firstname %> <%= project.project_owner.lastname %></center></td>
        <% else %>
        <td><center>N/A</center></td>
        <% end %>
        <td><center><%= link_to 'Show', project %></center></td>
        <% if current_user.admin? || (current_user.manager? && current_user.id == project.project_manager_id) %>
          <td><center><%= link_to 'Edit', edit_project_path(project) %></center></td>
        <% end %>
        <td><center><%= link_to 'Destroy', project, method: :delete, data: { confirm: "Are you sure?\nAll the files attached to the project will be deleted." } %></center></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<center>
<% if @projects.where(status: "Closed").size == 0 && @projects.where(status: "Delivered").size == 0 %>
  <h4>No completed projects</h4>
<% end %>
</center>

app/views/projects/manage.html.erb
<h1>Manage Project</h1>

<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @project.status != nil %>
    <div class="field">
      <strong>Status:</strong>
      <%= @project.status %>
    </div>
  <% end %>
  <% if current_user.admin? %>
    <div class="field">
      <%= f.label :project_manager_id %><br>
      <%= f.collection_select(:project_manager_id, User.all.where(manager: true), :id, :firstname, :prompt => true) %>
    </div>
  <% end %>
  <% if @project.confirmation? %>
    <div class="field">
      <%= f.label :cost %><br>
      <%= f.number_field :cost %>
      <%= f.collection_select(:currency_id, Currency.all, :id, :title, :prompt => true) %>
    </div>
    <div class="field">
      <%= f.label :deadline %><br>
      <%= f.date_select :deadline, {:include_blank => true, :default => nil} %>
    </div>
  <% end %>
  <%= submit_tag 'Save', :name => 'save' %>
<% end %>

<%= link_to 'Back', @project %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.title %></h2>
<p>
  <h3><%= @project.status %></h3>
</p>

<table width=100%>
  <tr>
    <td>
      <h3>Project Summary</h3>
      <p>
        <strong>User:</strong>
        <% if @project.project_owner_id != nil %>
          <%= @project.project_owner.firstname %> <%= @project.project_owner.lastname %>
        <% else %>
          N/A
        <% end %>
      </p>
      <p>
        <strong>Project Manager:</strong>
        <% if @project.project_manager_id != nil %>
          <%= @project.project_manager.firstname %> <%= @project.project_manager.lastname %>
          <% else %>
          N/A
        <% end %>
      </p>
      <p>
        <strong>Category:</strong>
        <%= @project.category.name %>
      </p>
      <p>
        <strong>Title:</strong>
        <%= @project.title %>
      </p>
      <p>
        <strong>Starting date:</strong>
        <% if @project.starting != nil %>
          <%= @project.starting %>
        <% else %>
          N/A
        <% end %>
      </p>
      <p>
        <strong>Deadline:</strong>
        <% if @project.deadline != nil %>
          <%= @project.deadline %>
        <% else %>
          N/A
        <% end %>
      </p>
      <% if @project.deadline != nil && @project.starting != nil %>
        <p>
          <strong>Progress:</strong>
            <% if (@project.deadline - @project.starting).to_i == 0 || @project.status == "Closed" || @project.status == "Delivered" %>
              100%
            <% else %>
              <%= ((100/(@project.deadline - @project.starting).to_i * (Date.today - @project.starting)).to_i).to_s+'%'%>
            <% end %>
        </p>
      <% end %>
      <p>
        <strong>Urgency:</strong>
        <%= @project.urgency %>
      </p>
      <p>
        <strong>Cost:</strong>
        <% if @project.cost != nil %>
          <%= @project.cost %>
          <% if @project.currency != nil %>
            <%= @project.currency.title %>
          <% end %>
        <% else %>
          N/A
        <% end %>
      </p>
    </td>
    <td>
      <h3>Description</h3>
      <p>
        <%= @project.description %>
      </p>
      <h3>Instruction</h3>
      <p>
        <%= @project.instruction %>
      </p>
      <p>
        <%= render "input_files/index" %>
      </p>
    </td>
    <td>
      <p>
        <%= render "quotations/index" %>
      </p>
      <p>
        <% if @project.status == 'Quote' && (current_user == @project.project_owner || (current_user.company_admin? && current_user.company_id == @project.company_id)) %>
            <%= button_to "Approuve", { :controller => :projects, action: "accept", :id => @project.id}, :method => :post %>
        <% end %>

        <% if @project.status == 'Ongoing' && (current_user == @project.project_owner || (current_user.company_admin? && current_user.company_id == @project.company_id)) %>
            <%= button_to "Reject", { :controller => :projects, action: "reject", :id => @project.id}, :method => :post %>
        <% end %>
      </p>
      <p>
        <%= render "invoices/index" %>
      </p>
      <p>
        <%= render "output_files/index" %>
      </p>
    </td>
  </tr>
</table>

<% if (@project.status != "Delivered" && @project.status != "Closed") || current_user.admin? || (current_user.manager? && current_user.id == @project.project_manager_id) %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>

<% if current_user.admin? || (current_user.manager? && current_user.id == @project.project_manager_id && @project.confirmation?) %>
  <%= link_to 'Manage', manage_project_path(@project) %> |
<% end %>

<% if (current_user == @project.project_owner || current_user == @project.project_manager) && @project.project_manager_id != nil %>
  <%= link_to 'Send message', new_message_path %> |
<% end %>

<%= link_to 'Back', projects_path %>