config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/projects')

  resources :messages
  resources :projects
  resources :companies

  devise_for :admins
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users

  resources :projects do
    resources :input_files
    resources :quotations
    resources :invoices
    resources :output_files
  end
  
  get 'pages/info'
  get 'companies/:id/invitations/new' => 'invitations#new'
  post 'companies/:id/invitations' => 'invitations#create', :as => :invitations
  post 'projects/:id/accept' => 'projects#accept'
  post 'projects/:id/reject' => 'projects#reject'
  post 'companies/:id/leave' => 'companies#leave'
  get 'projects/:id/manage', to: 'projects#manage', :as => :manage_project
  post 'users/:id/grantManager' => 'users#grantManager'
  post 'users/:id/removeManagerPriv' => 'users#removeManagerPriv'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get '/storage/inputFiles/:id/:basename.:extension' => 'input_files#download'
  get '/storage/quotations/:id/:basename.:extension' => 'quotations#download'
  get '/storage/invoices/:id/:basename.:extension' => 'invoices#download'
  get '/storage/outputFiles/:id/:basename.:extension' => 'output_files#download'

  match 'projects/:project_id/input_files/:id' => 'input_files#destroy', :via => :delete, :as => :destroy_input_file
  match 'projects/:project_id/quotations/:id' => 'quotations#destroy', :via => :delete, :as => :destroy_quotation
  match 'projects/:project_id/invoices/:id' => 'invoices#destroy', :via => :delete, :as => :destroy_invoice
  match 'projects/:project_id/output_files/:id' => 'output_files#destroy', :via => :delete, :as => :destroy_output_file

end

app/models/input_file.rb
class InputFile < ActiveRecord::Base
	mount_uploader :file_path, FileUploader
	belongs_to :project

	validates :file_path, presence: true
end

app/controllers/input_files_controller.rb
class InputFilesController < ApplicationController
  before_action :set_input_file, only: [:update, :destroy, :download]
  before_action :set_project, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :set_project_download, only: [:download]
  before_action :check_company
  before_action :check_auth

  # GET /input_files
  # GET /input_files.json
  def index
    @input_files = @project.input_files
  end

  # GET /input_files/new
  def new
    @input_file = InputFile.new
  end

  # POST /input_files
  # POST /input_files.json
  def create
    @input_file = InputFile.new(input_file_params)
    respond_to do |format|
      if @input_file.save
        @input_file.update_attribute(:project_id, @project.id)
        # Send email notification to Admins and PM of the project
        ExampleMailer.new_input_file(@project).deliver
        format.html { redirect_to @project, notice: 'Client file was successfully created.' }
        format.json { render :show, status: :created, location: @input_file }
      else
        format.html { render :new }
        format.json { render json: @input_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /input_files/1
  # DELETE /input_files/1.json
  def destroy
    @input_file.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Client file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Download the file
  def download
    path = "#{@input_file.file_path}"
    send_file path, :x_sendfile=>true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input_file
      @input_file = InputFile.find(params[:id])
    end

    # Set the project of the file
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Set the project of the file to download
    def set_project_download
      @project = Project.find(@input_file.project_id)
    end

    # Check if the current user belongs to a company or if they are an administrator or a project manager.
    def check_company
      if current_user.company == nil && !current_user.manager? && !current_user.admin?
        redirect_to new_company_path, :alert => "You have to create or be invited by a company before access to the website." and return
      end
    end

    # Check if the current user has the right to manage the client files of the current project.
    def check_auth
      if @project.project_owner_id != current_user.id && !current_user.admin? && current_user.id != @project.project_manager_id && !(current_user.company == @project.project_owner.company && current_user.company_admin?)
        redirect_to projects_path, :alert => "Access denied." and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def input_file_params
      params.require(:input_file).permit(:name, :file_path, :project_id)
    end
end

app/helpers/input_files_helper.rb
module InputFilesHelper
end

app/views/input_files/_form.html.erb
<%= form_for [@project, @input_file] do |f| %>
  <% if @input_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@input_file.errors.count, "error") %> prohibited this input_file from being saved:</h2>
      <ul>
      <% @input_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file_path %><br>
    <%= f.file_field :file_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/input_files/_index.html.erb
<h3>Client files</h3>
<% if @project.input_files.size != 0 %>
  <table>
  	<thead>
  	    <tr>
  	      <th><center>Name</center></th>
  	      <th><center>File</center></th>
  	      <th><center>Action</center></th>
  	      <th colspan="2"></th>
  	    </tr>
    	<tbody>

      <% @project.input_files.each do |input_file| %>
        <tr>
        	<% if input_file.name != nil && input_file.name != "" %>
        		<td><center><%= input_file.name %></center></td>
        	<% else %>
        		<td><center>N/A</center></td>
        	<% end %>
          <td><center><%= link_to File.basename(input_file.file_path.url.to_s), "/storage/inputFiles/#{input_file.id}/#{File.basename(input_file.file_path.url.to_s)}" %></center></td>
          <td><center><%= link_to "Download", "/storage/inputFiles/#{input_file.id}/#{File.basename(input_file.file_path.url.to_s)}" %></center></td>
          <td><center><%= link_to "Destroy", destroy_input_file_path(@project.id, input_file.id), method: :delete, data: { confirm: "Are you sure ?" } %></center></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<p>No file submitted.</p>
<% end %>

<%= link_to "Add File", new_project_input_file_path(@project) %>

app/views/input_files/new.html.erb
<h1>New Client file</h1>

<%= render 'form' %>

<%= link_to 'Skip', @project %>